### ISSUE TITLE
Add ability to switch between env simply

### ISSUE THREAD

**Issue by amiragami84** [tool3/kpods#15]
Hi,
Currently, tokens are defined in bash profile (KP_TOKEN & KP_URL) file and i need to override the values in order to switch between qa and prod env for example.

Is there a way to retain both settings of more than one env (KP_TOKEN_QA, KP_TOKEN_PROD)
and then to simply switch between environments?

Thanks,
Agami

**Comment by amiragami84** [comment]
Issue is fixed.

1. We created 2 properties file in home directory:
~/KP_TEST.properties
~/KP_PROD.properties

2. When need to switch between envs, simply typing the following:
export $(cat ~/KP_PROD.properties)
OR
export $(cat ~/KP_TEST.properties)

and that's all!
Closed.

**Comment by tool3** [comment]
let’s document this!
