### ISSUE TITLE
Add watch pod logs

### ISSUE THREAD

**Issue by amiragami84** [tool3/kpods#16]
Add ability to watch pods logs, to achieve the same as:
while sleep 1; do kp logs site-consumer-qa-5b5d746bdc-qvwsq; done

(without getting the KP ascii between intervals... )

**Comment by tool3** [comment]
Great idea!   
I also think `-w, --watch` would be a great flag name, or `-t, --tail` you decide 🤗

**Comment by tool3** [comment]
okay so I decided myself - we can't use `tail` because that's gonna interfere with `-t` for `token`
