### ISSUE TITLE
Add izerto_env value to kp get

### ISSUE THREAD

**Issue by amiragami84** [tool3/kpods#9]
Hi Tal,
I would be more than happy if you can add the IZERTO_ENV column(e.g qa_k8s,  qa_k8s_for_e2e etc..) to the existing table.

Thanks,
Agami

**Comment by tool3** [comment]
hi agami the great,
since this information is at the pod level - the current API used for the general pods list - does not contain this information.

I am working on a multipod view which will contain this information for a subset of pods (#12).

Thanks ! ❤️
